### ISSUE TITLE
Invalid tooltip position

### ISSUE THREAD

**Issue by kayden-fi** [chromatic-protocol/frontend#428]
![image](https://github.com/chromatic-protocol/frontend/assets/123065972/0a32889b-dd9e-4d0a-a5dc-57063a1c3fb4)

**Comment by dia-nn** [comment]
@jaycho-46 
I think it is because the `label` prop of `TooltipAlert` is same. 
Now it is connected by `class` name but it can be changed to `id`. If something should be updated, let me know.
