### ISSUE TITLE
style issue

### ISSUE THREAD

**Issue by jaycho-46** [chromatic-protocol/frontend#459]
@dia-nn 
<img width="1173" alt="Screenshot 2023-08-11 at 1 39 57 PM" src="https://github.com/chromatic-protocol/frontend/assets/123064207/72a8d3d4-d17a-4719-9b01-bf5f55ec5453">

test url: latest deploy (https://deploy-preview-457--preview-testnet-chromatic-protocol.netlify.app/)

- wallet popover button
- leverage select button
- sell/buy button

**Comment by dia-nn** [comment]
fixed this issue with dark mode.
https://github.com/chromatic-protocol/frontend/pull/454
